// checksum 0x9a77 version 0x30001
/*
  This file was generated by the Mobile Qt Application wizard of Qt Creator.
  MainWindow is a convenience class containing mobile device specific code
  such as screen orientation handling.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QtGui/QMainWindow>
#include <QProcess>

namespace Ui {
    class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT
public:
    enum ScreenOrientation {
        ScreenOrientationLockPortrait,
        ScreenOrientationLockLandscape,
        ScreenOrientationAuto
    };

    QTimer *countdown;

    explicit MainWindow(QWidget *parent = 0);
    virtual ~MainWindow();

    void setOrientation(ScreenOrientation orientation);
    void showExpanded();
    void reset_buttons();
    void load_alarms();
    void init_alarms();
    void show_alarms();
    void time_checker();
    void update();
    void processError(QProcess::ProcessError err);

private:
    Ui::MainWindow *ui;
    QProcess *process;
    int startMilliseconds;

protected slots:
    void timeOut();


private slots:
    void on_btn_alarm_clicked();
    void on_btn_sleep_clicked();
    void on_btn_close_clicked();
    void on_btn_hide_clicked();

    void on_btn_new_clicked();

    void on_btn_save_clicked();
    void on_btn_cancel_clicked();

    void on_btn_left_clicked();
    void on_btn_right_clicked();

    void on_btn_frm_1_clicked();
    void on_btn_frm_2_clicked();
    void on_btn_frm_3_clicked();
    void on_btn_frm_4_clicked();
    void on_btn_frm_5_clicked();
    void on_btn_frm_6_clicked();

    void on_btn_sun_clicked();
    void on_btn_mon_clicked();
    void on_btn_tue_clicked();
    void on_btn_wed_clicked();
    void on_btn_thu_clicked();
    void on_btn_fri_clicked();
    void on_btn_sat_clicked();

    void on_btn_start_clicked();
};

#endif // MAINWINDOW_H
